# Generated by Django 6.0 on 2025-12-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('operateur', models.CharField(choices=[('Orange Money', 'Orange Money'), ('MTN Money', 'MTN Money')], max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gagnant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.IntegerField(choices=[(1, '1er'), (2, '2e'), (3, '3e')])),
                ('date_tirage', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tirage.inscription')),
            ],
        ),
    ]
